/**
 * Static data loader. The CSV-derived JSON ships in /static/data/articles.json
 * (generated by `fakethirtyeight build-site-data`). We import it once and
 * memoize derived indexes by id, year, byline-slug, and kind.
 *
 * Runs in two environments:
 *   - Browser at runtime: fetch the JSON over HTTP.
 *   - Node at build time (svelte-kit prerender entries generators):
 *     read it directly from disk.
 */
import type { Entry } from './types';
import { base } from '$app/paths';
import { browser } from '$app/environment';

export interface DataCache {
	all: Entry[];
	byId: Map<string, Entry>;
	byYear: Map<number, Entry[]>;
	byBylineSlug: Map<string, { name: string; entries: Entry[] }>;
	years: number[];
}

let cache: DataCache | null = null;

const DIACRITICS = /[̀-ͯ]/g;

export function slugify(text: string): string {
	if (!text) return '';
	return text
		.normalize('NFKD')
		.replace(DIACRITICS, '')
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');
}

async function fetchEntries(fetcher: typeof fetch): Promise<Entry[]> {
	const resp = await fetcher(`${base}/data/articles.json`);
	if (!resp.ok) throw new Error(`failed to load articles.json: ${resp.status}`);
	return resp.json();
}

async function readEntriesFromDisk(): Promise<Entry[]> {
	const [{ readFile }, { resolve }] = await Promise.all([
		import('node:fs/promises'),
		import('node:path')
	]);
	// At build time SvelteKit's CWD is the `web/` folder, so the data file
	// lives at static/data/articles.json relative to there.
	const path = resolve(process.cwd(), 'static/data/articles.json');
	const text = await readFile(path, 'utf8');
	return JSON.parse(text);
}

export async function loadEntries(fetcher?: typeof fetch): Promise<DataCache> {
	if (cache) return cache;

	const all = browser && fetcher ? await fetchEntries(fetcher) : await readEntriesFromDisk();

	const byId = new Map<string, Entry>();
	const byYear = new Map<number, Entry[]>();
	const byBylineSlug = new Map<string, { name: string; entries: Entry[] }>();

	for (const entry of all) {
		byId.set(entry.id, entry);

		if (entry.year != null) {
			let arr = byYear.get(entry.year);
			if (!arr) {
				arr = [];
				byYear.set(entry.year, arr);
			}
			arr.push(entry);
		}

		for (const author of entry.authors) {
			const slug = slugify(author);
			if (!slug) continue;
			let bucket = byBylineSlug.get(slug);
			if (!bucket) {
				bucket = { name: author, entries: [] };
				byBylineSlug.set(slug, bucket);
			}
			bucket.entries.push(entry);
		}
	}

	// Oldest year first — this is a chronological retrospective.
	const years = [...byYear.keys()].sort((a, b) => a - b);

	cache = { all, byId, byYear, byBylineSlug, years };
	return cache;
}
