/**
 * Static data loader. The CSV-derived JSON ships in /static/data/articles.json
 * (generated by `fakethirtyeight build-site-data`). We import it once and
 * memoize derived indexes by id, year, byline-slug, and kind.
 *
 * Runs in two environments:
 *   - Browser at runtime: fetch the JSON over HTTP.
 *   - Node at build time (svelte-kit prerender entries generators):
 *     read it directly from disk.
 */
import type { Entry } from './types';
import { base } from '$app/paths';
import { browser } from '$app/environment';

export interface DataCache {
	all: Entry[];
	byId: Map<string, Entry>;
	byYear: Map<number, Entry[]>;
	byYearMonth: Map<string, Entry[]>; // key: "YYYY-MM"
	byBylineSlug: Map<string, { name: string; entries: Entry[] }>;
	years: number[];
	/** Sorted list of YYYY-MM keys per year, e.g. monthsByYear.get(2020) → ["2020-01", "2020-02", …]. */
	monthsByYear: Map<number, string[]>;
}

const MONTH_LABELS: Record<string, string> = {
	'01': 'January',
	'02': 'February',
	'03': 'March',
	'04': 'April',
	'05': 'May',
	'06': 'June',
	'07': 'July',
	'08': 'August',
	'09': 'September',
	'10': 'October',
	'11': 'November',
	'12': 'December'
};

export function monthLabel(mm: string): string {
	return MONTH_LABELS[mm] ?? mm;
}

let cache: DataCache | null = null;

const DIACRITICS = /[̀-ͯ]/g;

export function slugify(text: string): string {
	if (!text) return '';
	return text
		.normalize('NFKD')
		.replace(DIACRITICS, '')
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');
}

async function fetchEntries(fetcher: typeof fetch): Promise<Entry[]> {
	const resp = await fetcher(`${base}/data/articles.json`);
	if (!resp.ok) throw new Error(`failed to load articles.json: ${resp.status}`);
	return resp.json();
}

async function readEntriesFromDisk(): Promise<Entry[]> {
	const [{ readFile }, { resolve }] = await Promise.all([
		import('node:fs/promises'),
		import('node:path')
	]);
	// At build time SvelteKit's CWD is the `web/` folder, so the data file
	// lives at static/data/articles.json relative to there.
	const path = resolve(process.cwd(), 'static/data/articles.json');
	const text = await readFile(path, 'utf8');
	return JSON.parse(text);
}

export async function loadEntries(fetcher?: typeof fetch): Promise<DataCache> {
	if (cache) return cache;

	const all = browser && fetcher ? await fetchEntries(fetcher) : await readEntriesFromDisk();

	const byId = new Map<string, Entry>();
	const byYear = new Map<number, Entry[]>();
	const byYearMonth = new Map<string, Entry[]>();
	const byBylineSlug = new Map<string, { name: string; entries: Entry[] }>();

	for (const entry of all) {
		byId.set(entry.id, entry);

		if (entry.year != null) {
			let arr = byYear.get(entry.year);
			if (!arr) {
				arr = [];
				byYear.set(entry.year, arr);
			}
			arr.push(entry);

			// `date` is either an ISO timestamp, YYYY-MM-DD, or YYYY-MM.
			// Only bucket by month when we have at least YYYY-MM precision.
			const ym = entry.date && entry.date.length >= 7 ? entry.date.slice(0, 7) : null;
			if (ym && /^\d{4}-\d{2}$/.test(ym)) {
				let bucket = byYearMonth.get(ym);
				if (!bucket) {
					bucket = [];
					byYearMonth.set(ym, bucket);
				}
				bucket.push(entry);
			}
		}

		for (const author of entry.authors) {
			const slug = slugify(author);
			if (!slug) continue;
			let bucket = byBylineSlug.get(slug);
			if (!bucket) {
				bucket = { name: author, entries: [] };
				byBylineSlug.set(slug, bucket);
			}
			bucket.entries.push(entry);
		}
	}

	// Oldest year first — this is a chronological retrospective.
	const years = [...byYear.keys()].sort((a, b) => a - b);

	// Per-year ordered list of YYYY-MM keys, ascending.
	const monthsByYear = new Map<number, string[]>();
	for (const ym of byYearMonth.keys()) {
		const year = Number(ym.slice(0, 4));
		let arr = monthsByYear.get(year);
		if (!arr) {
			arr = [];
			monthsByYear.set(year, arr);
		}
		arr.push(ym);
	}
	for (const arr of monthsByYear.values()) arr.sort();

	cache = { all, byId, byYear, byYearMonth, byBylineSlug, years, monthsByYear };
	return cache;
}
