import csv
import gzip
from pathlib import Path

from PIL import Image

from fakethirtyeight import ai2html
from fakethirtyeight.ai2html import (
    _extract_one,
    _load_done,
    _load_render_done,
    _render_source_html,
)


def test_extract_one_finds_pym_ai2html_parent() -> None:
    html = """
    <html><body>
      <figure>
        <div id="ai2html_block_659273a59c45e" class=""></div>
        <figcaption>Original chart caption.</figcaption>
      </figure>
      <script>
      var pym_ai2html_block_659273a59c45e = new pym.Parent(
        'ai2html_block_659273a59c45e',
        'https://fivethirtyeight.com/?ai2html=https%3A%2F%2Ffivethirtyeight.com%2Fwp-content%2Fuploads%2F2023%2F04%2Frakich_TESTER-TOP-TWO_0410_1-4.html',
        { title: 'Stacked bar chart showing the candidate\\'s votes.' }
      )
      </script>
    </body></html>
    """

    rows = _extract_one(
        html, "data/articles/2024/example.html.gz", "https://example.com/article/"
    )

    assert len(rows) == 1
    assert rows[0]["kind"] == "pym"
    assert rows[0]["child_id"] == "ai2html_block_659273a59c45e"
    assert rows[0]["canonical_url"] == (
        "https://fivethirtyeight.com/wp-content/uploads/2023/04/"
        "rakich_TESTER-TOP-TWO_0410_1-4.html"
    )
    assert rows[0]["title"] == "Stacked bar chart showing the candidate's votes."
    assert rows[0]["caption"] == "Original chart caption."
    assert rows[0]["identifier"].startswith("fivethirtyeight-ai2html-")


def test_extract_one_finds_inline_generated_ai2html_block() -> None:
    html = """
    <html><body>
      <div class="container ai2html-container">
        <div id="g-vote-shift-state-maps-box" class="ai2html">
          <!-- Generated by ai2html v0.61 - 2016-10-11 - 16:13 -->
          <style>.g-artboard { margin: 0 auto; }</style>
          <div id="g-vote-shift-state-maps-Artboard_1" class="g-artboard"></div>
        </div>
      </div>
    </body></html>
    """

    rows = _extract_one(
        html, "data/articles/2019/example.html.gz", "https://example.com/article/"
    )

    assert len(rows) == 1
    assert rows[0]["kind"] == "inline"
    assert rows[0]["child_id"] == "g-vote-shift-state-maps-box"
    assert rows[0]["canonical_url"] == (
        "inline:data/articles/2019/example.html.gz#g-vote-shift-state-maps-box"
    )
    assert rows[0]["title"] == "vote shift state maps"


def test_load_done_ignores_logged_non_ai2html_files(
    tmp_path: Path, monkeypatch
) -> None:
    root = tmp_path
    ok = root / "ok.html"
    ok.write_text(
        "<div class='ai2html'><!-- Generated by ai2html v0.1 --></div>",
        encoding="utf-8",
    )
    bad = root / "bad.html"
    bad.write_text("<html>ordinary page</html>", encoding="utf-8")
    log_path = tmp_path / "ai2html_download_log.csv"

    with log_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=ai2html.LOG_FIELDS)
        writer.writeheader()
        writer.writerow(
            {
                "identifier": "ok",
                "canonical_url": "https://example.com/ok.html",
                "file_path": ok.name,
                "bytes": str(ok.stat().st_size),
                "content_type": "text/html",
                "fetched_via": "live",
                "status": "ok",
                "error": "",
            }
        )
        writer.writerow(
            {
                "identifier": "bad",
                "canonical_url": "https://example.com/bad.html",
                "file_path": bad.name,
                "bytes": str(bad.stat().st_size),
                "content_type": "text/html",
                "fetched_via": "live",
                "status": "ok",
                "error": "",
            }
        )

    assert _load_done(log_path, root=root) == {"https://example.com/ok.html"}


def test_download_ai2html_reextracts_inline_blocks(tmp_path: Path, monkeypatch) -> None:
    data_dir = tmp_path / "data"
    article = data_dir / "articles" / "2019" / "example.html.gz"
    article.parent.mkdir(parents=True)
    html = """
    <div id="g-inline-box" class="ai2html">
      <!-- Generated by ai2html v0.61 -->
      <div class="g-artboard"></div>
    </div>
    """
    with gzip.open(article, "wt", encoding="utf-8") as fh:
        fh.write(html)

    refs_path = tmp_path / "refs.csv"
    with refs_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=ai2html.REF_FIELDS)
        writer.writeheader()
        writer.writerow(
            {
                "identifier": ai2html.identifier_for(
                    "inline:data/articles/2019/example.html.gz#g-inline-box"
                ),
                "article_file": "data/articles/2019/example.html.gz",
                "article_url": "https://example.com/article/",
                "ai2html_url": "",
                "canonical_url": "inline:data/articles/2019/example.html.gz#g-inline-box",
                "child_id": "g-inline-box",
                "title": "inline",
                "caption": "",
                "kind": "inline",
            }
        )

    monkeypatch.setattr(ai2html, "DATA_DIR", data_dir)
    ok, skipped, failed = ai2html.download_ai2html(
        workers=1,
        refs_path=refs_path,
        out_dir=data_dir / "ai2html",
        log_path=data_dir / "ai2html_download_log.csv",
    )

    assert (ok, skipped, failed) == (1, 0, 0)
    rows = list(csv.DictReader((data_dir / "ai2html_download_log.csv").open()))
    assert rows[0]["status"] == "ok"
    assert rows[0]["fetched_via"] == "article"
    out_path = tmp_path / rows[0]["file_path"]
    assert "Generated by ai2html" in out_path.read_text(encoding="utf-8")


def test_render_source_html_wraps_inline_fragment() -> None:
    wrapped = _render_source_html(
        "<div class='ai2html'>chart</div>",
        "https://fivethirtyeight.com/wp-content/uploads/2023/04/chart.html",
        base_url="",
    )

    assert "<!doctype html>" in wrapped
    assert (
        '<base href="https://fivethirtyeight.com/wp-content/uploads/2023/04/chart.html">'
        in wrapped
    )
    assert "max-width: 1000px" in wrapped


def test_load_render_done_requires_existing_png(tmp_path: Path) -> None:
    root = tmp_path
    ok = root / "data" / "ai2html_renders" / "ok.png"
    ok.parent.mkdir(parents=True)
    Image.new("RGB", (10, 10), (0, 0, 0)).save(ok)
    log_path = root / "data" / "ai2html_render_log.csv"
    with log_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=ai2html.RENDER_LOG_FIELDS)
        writer.writeheader()
        writer.writerow(
            {
                "identifier": "ok",
                "canonical_url": "https://example.com/ok.html",
                "file_path": "data/ai2html/ok.html",
                "render_path": "data/ai2html_renders/ok.png",
                "bytes": "3",
                "width": "10",
                "height": "10",
                "status": "ok",
                "error": "",
            }
        )
        writer.writerow(
            {
                "identifier": "missing",
                "canonical_url": "https://example.com/missing.html",
                "file_path": "data/ai2html/missing.html",
                "render_path": "data/ai2html_renders/missing.png",
                "bytes": "3",
                "width": "10",
                "height": "10",
                "status": "ok",
                "error": "",
            }
        )

    assert _load_render_done(log_path, root=root) == {"https://example.com/ok.html"}
