"""Extract and save ai2html graphics embedded in article HTML.

This runs parallel to :mod:`fakethirtyeight.images`: the reference stage
walks ``data/articles/**/*.html.gz`` and finds ai2html graphics, while the
download stage materializes each unique HTML graphic into ``data/ai2html/``.

FiveThirtyEight used two ai2html shapes:

* Older articles sometimes include the generated ai2html markup inline,
  usually under a ``class="ai2html"`` wrapper and a ``Generated by ai2html``
  comment.
* Newer ABC-era articles usually include an empty ``ai2html_block_*`` div and
  a ``new pym.Parent(...)`` script that points at a standalone
  ``?ai2html=<wp-content/uploads/...html>`` URL.
"""

from __future__ import annotations

import base64
import csv
import gzip
import hashlib
import html
import logging
import mimetypes
import re
import shutil
import subprocess
import tempfile
import threading
import time
from pathlib import Path
from urllib.parse import parse_qs, unquote, urljoin, urlparse, urlunparse

import httpx
from bs4 import BeautifulSoup, Comment
from bs4.element import Tag
from PIL import Image, ImageChops
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)
from tqdm import tqdm
from tqdm.contrib.concurrent import thread_map

from fakethirtyeight.articles import ARTICLES_DIR
from fakethirtyeight.http import make_client
from fakethirtyeight.images import _build_article_url_lookup
from fakethirtyeight.paths import DATA_DIR, ensure_dirs

log = logging.getLogger(__name__)

AI2HTML_REFS_FILE = DATA_DIR / "ai2html_references.csv"
AI2HTML_DIR = DATA_DIR / "ai2html"
AI2HTML_LOG = DATA_DIR / "ai2html_download_log.csv"
AI2HTML_RENDER_DIR = DATA_DIR / "ai2html_renders"
AI2HTML_RENDER_LOG = DATA_DIR / "ai2html_render_log.csv"

REF_FIELDS = (
    "identifier",
    "article_file",
    "article_url",
    "ai2html_url",
    "canonical_url",
    "child_id",
    "title",
    "caption",
    "kind",  # "pym" | "inline" | "url"
)

LOG_FIELDS = (
    "identifier",
    "canonical_url",
    "file_path",
    "bytes",
    "content_type",
    "fetched_via",  # "live" | "wayback" | "article" | ""
    "status",
    "error",
)

RENDER_LOG_FIELDS = (
    "identifier",
    "canonical_url",
    "file_path",
    "render_path",
    "bytes",
    "width",
    "height",
    "status",
    "error",
)

_IA_ID_PREFIX = "fivethirtyeight-ai2html-"
_AI2HTML_MARKER_RE = re.compile(r"Generated by ai2html", re.IGNORECASE)
_AI2HTML_BLOCK_RE = re.compile(r"ai2html_block_[a-z0-9]+", re.IGNORECASE)
_PYM_PARENT_RE = re.compile(
    r"new\s+pym\.Parent\(\s*"
    r"(?P<child_quote>['\"])(?P<child>ai2html_block_[^'\"]+)(?P=child_quote)\s*,\s*"
    r"(?P<url_quote>['\"])(?P<url>.*?)(?<!\\)(?P=url_quote)\s*,\s*"
    r"\{(?P<options>.*?)\}\s*\)",
    re.DOTALL,
)
_JS_TITLE_RE = re.compile(
    r"title\s*:\s*(?P<quote>['\"])(?P<title>.*?)(?<!\\)(?P=quote)",
    re.DOTALL,
)


def identifier_for(canonical_url: str) -> str:
    """Deterministic archive.org-style identifier for one ai2html graphic."""
    h = hashlib.sha1(canonical_url.encode("utf-8"), usedforsecurity=False).hexdigest()[
        :12
    ]
    return f"{_IA_ID_PREFIX}{h}"


def _canonicalize_url(url: str) -> str:
    p = urlparse(url)
    if not p.scheme and not p.netloc:
        return ""
    if p.scheme in {"data", "file"}:
        return ""
    if not p.scheme:
        p = p._replace(scheme="https")
    return urlunparse((p.scheme, p.netloc.lower(), p.path, "", "", ""))


def _ai2html_source_url(url: str) -> str:
    """Collapse a FiveThirtyEight ``?ai2html=`` wrapper to its source URL."""
    raw = html.unescape(url).strip()
    p = urlparse(raw)
    query = parse_qs(p.query)
    ai2html_values = query.get("ai2html") or []
    if ai2html_values:
        return _canonicalize_url(unquote(ai2html_values[0]))
    return _canonicalize_url(raw)


def _decode_js_string(text: str) -> str:
    return (
        html.unescape(text)
        .replace("\\'", "'")
        .replace('\\"', '"')
        .replace("\\/", "/")
        .replace("\\\\", "\\")
        .strip()
    )


def _caption_for(node: Tag) -> str:
    fig = node.find_parent("figure")
    if fig is None:
        return ""
    cap = fig.find("figcaption")
    if cap is None:
        return ""
    return cap.get_text(" ", strip=True)


def _attr_text(node: Tag, name: str) -> str:
    value = node.get(name) if hasattr(node, "get") else ""
    return value if isinstance(value, str) else ""


def _has_ai2html_marker(tag: Tag) -> bool:
    for comment in tag.find_all(string=lambda text: isinstance(text, Comment)):
        if _AI2HTML_MARKER_RE.search(str(comment)):
            return True
    return False


def _is_inline_ai2html_tag(tag: Tag) -> bool:
    classes = tag.get("class") or []
    if isinstance(classes, str):
        classes = classes.split()
    return "ai2html" in classes and _has_ai2html_marker(tag)


def _extract_inline_block(html_text: str, child_id: str) -> str:
    """Return serialized inline ai2html markup from an article source."""
    soup = BeautifulSoup(html_text, "lxml")
    if child_id:
        tag = soup.find(id=child_id)
        if isinstance(tag, Tag) and _has_ai2html_marker(tag):
            return str(tag)
    for tag in soup.find_all(_is_inline_ai2html_tag):
        tag_id = _attr_text(tag, "id")
        if not child_id or tag_id == child_id:
            return str(tag)
    return ""


def _extract_one(
    html_text: str, article_file: str, article_url: str
) -> list[dict[str, str]]:
    """Pull ai2html references out of one article's HTML."""
    soup = BeautifulSoup(html_text, "lxml")
    rows: list[dict[str, str]] = []
    seen: set[str] = set()

    def emit(
        *,
        canonical_url: str,
        ai2html_url: str,
        child_id: str,
        title: str,
        caption: str,
        kind: str,
    ) -> None:
        if not canonical_url or canonical_url in seen:
            return
        seen.add(canonical_url)
        rows.append(
            {
                "identifier": identifier_for(canonical_url),
                "article_file": article_file,
                "article_url": article_url,
                "ai2html_url": ai2html_url,
                "canonical_url": canonical_url,
                "child_id": child_id,
                "title": title,
                "caption": caption,
                "kind": kind,
            }
        )

    placeholders: dict[str, Tag] = {}
    for tag in soup.find_all(id=_AI2HTML_BLOCK_RE):
        if isinstance(tag, Tag):
            placeholders[_attr_text(tag, "id")] = tag

    for script in soup.find_all("script"):
        script_text = script.get_text("\n")
        if "ai2html" not in script_text:
            continue
        for match in _PYM_PARENT_RE.finditer(script_text):
            child_id = _decode_js_string(match.group("child"))
            raw_url = _decode_js_string(match.group("url"))
            canonical = _ai2html_source_url(raw_url)
            title_match = _JS_TITLE_RE.search(match.group("options"))
            title = _decode_js_string(title_match.group("title")) if title_match else ""
            placeholder = placeholders.get(child_id)
            caption = _caption_for(placeholder) if placeholder else ""
            emit(
                canonical_url=canonical,
                ai2html_url=raw_url,
                child_id=child_id,
                title=title,
                caption=caption,
                kind="pym",
            )

    for tag in soup.find_all(["a", "iframe"]):
        raw_url = _attr_text(tag, "src") or _attr_text(tag, "href")
        if "ai2html=" not in raw_url:
            continue
        canonical = _ai2html_source_url(raw_url)
        emit(
            canonical_url=canonical,
            ai2html_url=raw_url,
            child_id="",
            title=_attr_text(tag, "title") or _attr_text(tag, "aria-label"),
            caption=_caption_for(tag),
            kind="url",
        )

    for tag in soup.find_all(_is_inline_ai2html_tag):
        tag_id = _attr_text(tag, "id")
        if not tag_id:
            digest = hashlib.sha1(str(tag).encode(), usedforsecurity=False).hexdigest()[
                :12
            ]
            tag_id = f"inline-{digest}"
        canonical = f"inline:{article_file}#{tag_id}"
        emit(
            canonical_url=canonical,
            ai2html_url="",
            child_id=tag_id,
            title=tag_id.removeprefix("g-").removesuffix("-box").replace("-", " "),
            caption=_caption_for(tag),
            kind="inline",
        )

    return rows


def extract_references(
    *,
    articles_dir: Path = ARTICLES_DIR,
    out_path: Path = AI2HTML_REFS_FILE,
    enriched_path: Path | None = None,
) -> int:
    """Walk downloaded article HTML, emit one row per ai2html graphic."""
    if enriched_path is None:
        from fakethirtyeight.enrich import ENRICHED_FILE

        enriched_path = ENRICHED_FILE

    files = sorted(articles_dir.rglob("*.html.gz"))
    log.info("scanning %d article files", len(files))
    url_by_file = _build_article_url_lookup(enriched_path)
    log.info("loaded article URL lookup for %d files", len(url_by_file))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    n_rows = 0
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=REF_FIELDS)
        writer.writeheader()
        for f in tqdm(files, desc="extracting-ai2html", unit="article"):
            try:
                with gzip.open(f, "rt", errors="replace") as gh:
                    html_text = gh.read()
            except OSError:
                log.warning("could not read %s, skipping", f)
                continue
            if "ai2html" not in html_text.lower():
                continue
            rel = str(f.relative_to(DATA_DIR.parent))
            article_url = url_by_file.get(rel, "")
            for row in _extract_one(html_text, rel, article_url):
                writer.writerow(row)
                n_rows += 1

    log.info("wrote %d ai2html references to %s", n_rows, out_path)
    return n_rows


def _hash(canonical_url: str) -> str:
    return hashlib.sha1(
        canonical_url.encode("utf-8"), usedforsecurity=False
    ).hexdigest()


def path_for(canonical_url: str, base: Path = AI2HTML_DIR) -> Path:
    h = _hash(canonical_url)
    return base / h[:2] / f"{h}.html"


def render_path_for(canonical_url: str, base: Path = AI2HTML_RENDER_DIR) -> Path:
    h = _hash(canonical_url)
    return base / h[:2] / f"{h}.png"


def _is_ai2html_body(text: str) -> bool:
    haystack = text[:100_000].lower()
    return (
        "generated by ai2html" in haystack
        or "ai2html_block_" in haystack
        or "class='ai2html'" in haystack
        or 'class="ai2html"' in haystack
    )


@retry(
    retry=retry_if_exception_type(httpx.HTTPError),
    stop=stop_after_attempt(4),
    wait=wait_exponential(multiplier=2, min=2, max=30),
    reraise=True,
)
def _stream_html(client: httpx.Client, url: str) -> tuple[str, str]:
    with client.stream("GET", url, follow_redirects=True) as resp:
        if resp.status_code in {429, 500, 502, 503, 504}:
            raise httpx.HTTPStatusError(
                "retryable", request=resp.request, response=resp
            )
        resp.raise_for_status()
        body = ""
        for chunk in resp.iter_text(chunk_size=64 * 1024):
            body += chunk
        return body, resp.headers.get("content-type", "")


def _wayback_url_for(client: httpx.Client, canonical_url: str) -> str | None:
    try:
        resp = client.get(
            "https://archive.org/wayback/available",
            params={"url": canonical_url},
            timeout=20,
        )
        data = resp.json()
    except (httpx.HTTPError, ValueError):
        return None
    snap = (data.get("archived_snapshots") or {}).get("closest") or {}
    if not snap.get("available"):
        return None
    ts = snap.get("timestamp") or ""
    if not ts:
        return None
    return f"https://web.archive.org/web/{ts}id_/{canonical_url}"


def _try_fetch(
    client: httpx.Client, canonical_url: str
) -> tuple[str, str, str] | tuple[None, None, str]:
    try:
        text, ct = _stream_html(client, canonical_url)
        if text and _is_ai2html_body(text):
            return text, ct, "live"
        live_err = f"non-ai2html response: {ct or 'unknown content type'}"
    except Exception as live_exc:  # noqa: BLE001
        live_err = repr(live_exc)[:160]

    wb = _wayback_url_for(client, canonical_url)
    if not wb:
        return None, None, f"live: {live_err}; no wayback capture"
    try:
        text, ct = _stream_html(client, wb)
        if text and _is_ai2html_body(text):
            return text, ct, "wayback"
        return (
            None,
            None,
            f"live: {live_err}; wayback: non-ai2html response: {ct or 'unknown'}",
        )
    except Exception as wb_exc:  # noqa: BLE001
        return None, None, f"live: {live_err}; wayback: {repr(wb_exc)[:80]}"


def _logged_file_is_ai2html(
    row: dict[str, str], *, root: Path = DATA_DIR.parent
) -> bool:
    path = row.get("file_path") or ""
    if not path:
        return False
    p = root / path
    if not p.exists():
        return False
    return _is_ai2html_body(p.read_text(encoding="utf-8", errors="replace"))


def _load_done(log_path: Path, *, root: Path = DATA_DIR.parent) -> set[str]:
    if not log_path.exists():
        return set()
    out: set[str] = set()
    with log_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            if (
                (row.get("status") or "") == "ok"
                and row.get("canonical_url")
                and _logged_file_is_ai2html(row, root=root)
            ):
                out.add(row["canonical_url"])
    return out


def _load_render_done(log_path: Path, *, root: Path = DATA_DIR.parent) -> set[str]:
    if not log_path.exists():
        return set()
    out: set[str] = set()
    with log_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            path = row.get("render_path") or ""
            render_path = root / path
            if (
                (row.get("status") or "") == "ok"
                and row.get("canonical_url")
                and path
                and render_path.exists()
                and not _mostly_blank(render_path)
            ):
                out.add(row["canonical_url"])
    return out


def _collect_refs(refs_path: Path) -> list[dict[str, str]]:
    seen: set[str] = set()
    out: list[dict[str, str]] = []
    with refs_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            canonical = (row.get("canonical_url") or "").strip()
            if canonical and canonical not in seen:
                seen.add(canonical)
                out.append(row)
    return out


def _load_downloaded_ai2html(
    log_path: Path = AI2HTML_LOG, *, root: Path = DATA_DIR.parent
) -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    if not log_path.exists():
        return out
    with log_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            canonical = (row.get("canonical_url") or "").strip()
            file_path = (row.get("file_path") or "").strip()
            if (
                canonical
                and file_path
                and (row.get("status") or "") == "ok"
                and (root / file_path).exists()
            ):
                out[canonical] = row
    return out


def _load_article_wayback_lookup(enriched_path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not enriched_path.exists():
        return out
    with enriched_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            url = (row.get("url") or "").strip()
            ts = (row.get("snapshot_timestamp") or "").strip()
            wayback = (row.get("wayback_url") or "").strip()
            if not url or not ts or not wayback:
                continue
            year = ts[:4]
            uhash = hashlib.sha1(
                url.encode("utf-8"), usedforsecurity=False
            ).hexdigest()[:16]
            out[f"data/articles/{year}/{uhash}.html.gz"] = wayback
    return out


def _read_article_inline(row: dict[str, str]) -> tuple[str, str, str]:
    article_file = row.get("article_file") or ""
    child_id = row.get("child_id") or ""
    if not article_file:
        return "", "", "missing article_file"
    path = DATA_DIR.parent / article_file
    if not path.exists():
        return "", "", f"missing article source: {article_file}"
    try:
        with gzip.open(path, "rt", errors="replace") as gh:
            html_text = gh.read()
    except OSError as exc:
        return "", "", repr(exc)[:160]
    block = _extract_inline_block(html_text, child_id)
    if not block:
        return "", "", "inline ai2html block not found"
    return block, "text/html", "article"


def download_ai2html(
    *,
    workers: int = 8,
    limit: int | None = None,
    refs_path: Path = AI2HTML_REFS_FILE,
    out_dir: Path = AI2HTML_DIR,
    log_path: Path = AI2HTML_LOG,
) -> tuple[int, int, int]:
    """Save each unique ai2html graphic as local HTML.

    Returns ``(downloaded, skipped, failed)``. External graphics fetch
    live first, then Wayback. Inline graphics are re-extracted from the
    article source file.
    """
    ensure_dirs()
    out_dir.mkdir(parents=True, exist_ok=True)

    refs = _collect_refs(refs_path)
    log.info("collected %d unique ai2html references", len(refs))
    done = _load_done(log_path)
    pending = [row for row in refs if row["canonical_url"] not in done]
    log.info("%d already logged; %d to fetch", len(done), len(pending))
    if limit is not None:
        pending = pending[:limit]
        log.info("limit=%d, fetching %d", limit, len(pending))
    if not pending:
        return (0, len(done), 0)

    write_header = not log_path.exists()
    write_lock = threading.Lock()

    with (
        make_client() as client,
        log_path.open("a", newline="", encoding="utf-8") as fh,
    ):
        writer = csv.DictWriter(fh, fieldnames=LOG_FIELDS)
        if write_header:
            writer.writeheader()
            fh.flush()

        def _process(row: dict[str, str]) -> int:
            canonical = row["canonical_url"]
            ident = identifier_for(canonical)
            if canonical.startswith("inline:"):
                body, content_type, source = _read_article_inline(row)
                if not body:
                    body_or_none: str | None = None
                    error = source
                else:
                    body_or_none = body
                    error = ""
            else:
                body_or_none, content_type, source = _try_fetch(client, canonical)
                error = source if body_or_none is None else ""

            if body_or_none is None:
                with write_lock:
                    writer.writerow(
                        {
                            "identifier": ident,
                            "canonical_url": canonical,
                            "file_path": "",
                            "bytes": "0",
                            "content_type": "",
                            "fetched_via": "",
                            "status": "error",
                            "error": error[:200],
                        }
                    )
                    fh.flush()
                return 0

            out_path = path_for(canonical, base=out_dir)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(body_or_none, encoding="utf-8")
            with write_lock:
                writer.writerow(
                    {
                        "identifier": ident,
                        "canonical_url": canonical,
                        "file_path": str(out_path.relative_to(DATA_DIR.parent)),
                        "bytes": str(out_path.stat().st_size),
                        "content_type": content_type or "text/html",
                        "fetched_via": source,
                        "status": "ok",
                        "error": "",
                    }
                )
                fh.flush()
            return 1

        outcomes = thread_map(
            _process,
            pending,
            max_workers=workers,
            desc="downloading-ai2html",
            unit="html",
        )

    n_ok = sum(outcomes)
    return (n_ok, len(done), len(pending) - n_ok)


def _chrome_executable() -> str:
    candidates = (
        shutil.which("google-chrome"),
        shutil.which("chromium"),
        shutil.which("chromium-browser"),
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    )
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return candidate
    msg = "Chrome/Chromium executable not found; install Chrome or pass a PATH-visible chromium binary"
    raise RuntimeError(msg)


def _embed_render_images(source: str, base_url: str) -> str:
    """Inline screenshot image assets so Chrome rendering is deterministic."""
    soup = BeautifulSoup(source, "lxml")
    changed = False
    with make_client() as client:
        for tag in soup.find_all("img"):
            if not isinstance(tag, Tag):
                continue
            src = _attr_text(tag, "src")
            if not src or urlparse(src).scheme in {"data", "file"}:
                continue
            url = urljoin(base_url, src)
            try:
                resp = client.get(url, follow_redirects=True, timeout=30)
                resp.raise_for_status()
            except httpx.HTTPError:
                continue
            content_type = resp.headers.get("content-type", "").split(";", 1)[0]
            if not content_type.startswith("image/"):
                content_type = mimetypes.guess_type(src)[0] or "image/png"
            encoded = base64.b64encode(resp.content).decode("ascii")
            tag["src"] = f"data:{content_type};base64,{encoded}"
            changed = True
    return str(soup) if changed else source


def _render_source_html(source: str, canonical_url: str, *, base_url: str = "") -> str:
    """Return a complete document suitable for deterministic screenshotting."""
    base_url = base_url or canonical_url
    if not canonical_url.startswith("inline:"):
        parsed = urlparse(canonical_url)
        base_url = urlunparse((parsed.scheme, parsed.netloc, parsed.path, "", "", ""))
    if base_url:
        source = _embed_render_images(source, base_url)
    if "<html" in source[:500].lower():
        if base_url and "<base " not in source[:2000].lower():
            base_tag = f'<base href="{html.escape(base_url, quote=True)}">'
            if re.search(r"<head[^>]*>", source, flags=re.IGNORECASE):
                return re.sub(
                    r"(<head[^>]*>)",
                    rf"\1\n  {base_tag}",
                    source,
                    count=1,
                    flags=re.IGNORECASE,
                )
            return re.sub(
                r"(<html[^>]*>)",
                rf"\1<head>{base_tag}</head>",
                source,
                count=1,
                flags=re.IGNORECASE,
            )
        return source
    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <base href="{html.escape(base_url, quote=True)}">
  <style>
    html, body {{
      margin: 0;
      padding: 0;
      background: #fff;
    }}
    body {{
      width: 100%;
      max-width: 1000px;
      overflow: hidden;
    }}
  </style>
</head>
<body>
{source}
</body>
</html>
"""


def _trim_screenshot(path: Path) -> tuple[int, int]:
    """Crop white browser padding around a screenshot, keeping a small margin."""
    with Image.open(path) as im:
        rgba = im.convert("RGBA")
        bg = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
        diff = ImageChops.difference(rgba, bg)
        # Ignore very small anti-aliased differences in the browser background.
        diff = diff.convert("L").point(lambda p: 255 if p > 8 else 0)
        bbox = diff.getbbox()
        if bbox is None:
            rgba.save(path)
            return rgba.size
        left, top, right, bottom = bbox
        margin = 12
        cropped = rgba.crop(
            (
                max(left - margin, 0),
                max(top - margin, 0),
                min(right + margin, rgba.width),
                min(bottom + margin, rgba.height),
            )
        )
        if cropped.mode != "RGB":
            white = Image.new("RGB", cropped.size, (255, 255, 255))
            white.paste(cropped, mask=cropped.getchannel("A"))
            white.save(path)
            return white.size
        cropped.save(path)
        return cropped.size


def _mostly_blank(path: Path) -> bool:
    try:
        with Image.open(path) as im:
            gray = im.convert("L")
            histogram = gray.histogram()
            non_white = sum(histogram[:245])
            return non_white / (gray.width * gray.height) < 0.001
    except OSError:
        return True


def _render_one(
    *,
    canonical_url: str,
    file_path: Path,
    out_path: Path,
    chrome: str,
    base_url: str,
    width: int,
    height: int,
    timeout: int,
) -> tuple[int, int, int, str]:
    source = file_path.read_text(encoding="utf-8", errors="replace")
    body = _render_source_html(source, canonical_url, base_url=base_url)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="fte-ai2html-render-") as tmp:
        tmp_path = Path(tmp)
        html_path = tmp_path / "render.html"
        profile_path = tmp_path / "chrome-profile"
        html_path.write_text(body, encoding="utf-8")
        cmd = [
            chrome,
            "--headless",
            "--disable-gpu",
            "--disable-extensions",
            "--disable-dev-shm-usage",
            "--hide-scrollbars",
            "--no-first-run",
            "--no-default-browser-check",
            f"--user-data-dir={profile_path}",
            f"--window-size={width},{height}",
            "--run-all-compositor-stages-before-draw",
            "--virtual-time-budget=5000",
            f"--screenshot={out_path}",
            html_path.as_uri(),
        ]
        proc = subprocess.Popen(  # noqa: S603 - command is built from local executable and paths.
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        started = time.monotonic()
        deadline = started + timeout
        stable_size: int | None = None
        while time.monotonic() < deadline:
            if out_path.exists() and out_path.stat().st_size > 0:
                current_size = out_path.stat().st_size
                if current_size == stable_size and time.monotonic() - started >= 5:
                    break
                stable_size = current_size
            if proc.poll() is not None:
                break
            time.sleep(0.25)
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
        stdout, stderr = proc.communicate(timeout=3)
    if not out_path.exists() and proc.returncode not in {0, None}:
        return 0, 0, 0, (stderr or stdout or "chrome failed")[:240]
    if not out_path.exists():
        return 0, 0, 0, "chrome completed without writing screenshot"
    rendered_width, rendered_height = _trim_screenshot(out_path)
    if _mostly_blank(out_path):
        return 0, rendered_width, rendered_height, "render appears blank"
    return out_path.stat().st_size, rendered_width, rendered_height, ""


def render_ai2html(
    *,
    limit: int | None = None,
    width: int = 1000,
    height: int = 4096,
    timeout: int = 60,
    force: bool = False,
    refs_path: Path = AI2HTML_REFS_FILE,
    download_log_path: Path = AI2HTML_LOG,
    enriched_path: Path | None = None,
    out_dir: Path = AI2HTML_RENDER_DIR,
    log_path: Path = AI2HTML_RENDER_LOG,
) -> tuple[int, int, int]:
    """Render downloaded ai2html HTML files to desktop PNG screenshots."""
    if enriched_path is None:
        from fakethirtyeight.enrich import ENRICHED_FILE

        enriched_path = ENRICHED_FILE
    ensure_dirs()
    out_dir.mkdir(parents=True, exist_ok=True)

    refs = _collect_refs(refs_path)
    downloaded = _load_downloaded_ai2html(download_log_path)
    done = set() if force else _load_render_done(log_path)
    pending = [
        row
        for row in refs
        if row["canonical_url"] in downloaded and row["canonical_url"] not in done
    ]
    missing = len([row for row in refs if row["canonical_url"] not in downloaded])
    log.info(
        "%d ai2html refs; %d downloaded; %d already rendered; %d missing html; %d to render",
        len(refs),
        len(downloaded),
        len(done),
        missing,
        len(pending),
    )
    if limit is not None:
        pending = pending[:limit]
        log.info("limit=%d, rendering %d", limit, len(pending))
    if not pending:
        return (0, len(done), missing)

    chrome = _chrome_executable()
    wayback_by_file = _load_article_wayback_lookup(enriched_path)
    write_header = not log_path.exists()
    rendered = failed = 0
    with log_path.open("a", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=RENDER_LOG_FIELDS)
        if write_header:
            writer.writeheader()
        for row in tqdm(pending, desc="rendering-ai2html", unit="png"):
            canonical = row["canonical_url"]
            ident = identifier_for(canonical)
            source_row = downloaded[canonical]
            src_path = DATA_DIR.parent / source_row["file_path"]
            out_path = render_path_for(canonical, base=out_dir)
            try:
                size, png_width, png_height, error = _render_one(
                    canonical_url=canonical,
                    file_path=src_path,
                    out_path=out_path,
                    chrome=chrome,
                    base_url=wayback_by_file.get(row.get("article_file") or "")
                    or row.get("article_url")
                    or canonical,
                    width=width,
                    height=height,
                    timeout=timeout,
                )
            except Exception as exc:  # noqa: BLE001
                size, png_width, png_height, error = 0, 0, 0, repr(exc)[:240]

            if error:
                failed += 1
                status = "error"
                render_path = ""
            else:
                rendered += 1
                status = "ok"
                render_path = str(out_path.relative_to(DATA_DIR.parent))
            writer.writerow(
                {
                    "identifier": ident,
                    "canonical_url": canonical,
                    "file_path": source_row["file_path"],
                    "render_path": render_path,
                    "bytes": str(size),
                    "width": str(png_width),
                    "height": str(png_height),
                    "status": status,
                    "error": error,
                }
            )
            fh.flush()

    return (rendered, len(done), failed + missing)
